#!/usr/bin/env python3
"""Build runtime packages from the canonical pstack source; never install them."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess

import yaml

SOURCE = Path(__file__).resolve().parents[1]
HYBRID = SOURCE / 'hybrid'
NAME = 'hstack'


def build(output):
    output = Path(output).resolve()
    if output == SOURCE or SOURCE.is_relative_to(output) or output.is_relative_to(SOURCE):
        raise ValueError('Output must not replace source or live inside canonical skills')
    marker = output / '.hstack-build'
    if output.exists() and any(output.iterdir()):
        if not marker.exists():
            raise ValueError('Refusing to replace an unmarked output directory')
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    marker.write_text('Generated by pstack/hybrid/build.py\n')
    revision = subprocess.check_output(['git', '-C', str(SOURCE), 'rev-parse', 'HEAD'], text=True).strip()
    digest = hashlib.sha256()
    for path in sorted(SOURCE.rglob('*')):
        if not path.is_file() or any(x in path.parts for x in ('node_modules', '__pycache__', 'dist', '.venv')) or path.is_relative_to(output):
            continue
        digest.update(str(path.relative_to(SOURCE)).encode() + b'\0' + path.read_bytes())
    fingerprint = digest.hexdigest()
    upstream = json.loads((SOURCE / '.cursor-plugin/plugin.json').read_text())
    for runtime in ('cursor', 'codex'):
        target = output / runtime / 'plugins' / NAME
        target.mkdir(parents=True)
        for directory in ('skills', 'agents', 'assets', 'docs', 'automations', 'hybrid'):
            shutil.copytree(SOURCE / directory, target / directory,
                            ignore=shutil.ignore_patterns('node_modules', '__pycache__', 'dist', '.venv', '*.pyc'))
        for filename in ('LICENSE', 'README.md'):
            shutil.copy2(SOURCE / filename, target / filename)
        for skill in sorted((target / 'skills').glob('*/SKILL.md')):
            match = re.match(r'^---\n(.*?)\n---\n', skill.read_text(), re.S)
            if not match:
                raise ValueError(f'Missing frontmatter: {skill}')
            metadata = yaml.safe_load(match[1])
            body = skill.read_text()[match.end():].lstrip()
            if runtime == 'codex':
                explicit = metadata.get('disable-model-invocation', False)
                metadata = {'name': skill.parent.name, 'description': metadata['description']}
                if explicit:
                    policy = skill.parent / 'agents/openai.yaml'
                    policy.parent.mkdir(exist_ok=True)
                    # Codex cloud omits explicit-only workflows from its initial catalog.
                    policy.write_text(yaml.safe_dump({'interface': {'display_name': metadata['name'], 'short_description': metadata['description'][:64]}, 'policy': {'allow_implicit_invocation': metadata['name'] == 'poteto-mode'}}, sort_keys=False))
            preamble = f'Before following this workflow, read [the {runtime} runtime adapter](../../hybrid/runtime/{runtime}.md). It governs runtime-specific instructions throughout this package.\n\n'
            skill.write_text('---\n' + yaml.safe_dump(metadata, sort_keys=False, allow_unicode=True) + '---\n\n' + preamble + body)
        if runtime == 'codex':
            (target / 'references').mkdir()
            shutil.copy2(HYBRID / 'runtime/codex.md', target / 'references/codex-runtime.md')
            (target / 'config').mkdir()
            shutil.copy2(HYBRID / 'runtime/default-models.json', target / 'config/default-models.json')
            shutil.copy2(HYBRID / 'runtime/setup-codex.md', target / 'skills/setup-pstack/SKILL.md')
            manifest = {'name': NAME, 'version': upstream['version'] + '+hstack.' + fingerprint[:12],
                        'description': 'hstack: pstack workflows for Codex CLI and desktop, with optional hybrid execution.',
                        'author': upstream['author'], 'license': 'MIT', 'repository': 'https://github.com/huankoh/plugins',
                        'skills': './skills/', 'interface': {'displayName': 'hstack', 'shortDescription': 'hstack for Cursor and Codex', 'longDescription': 'All pstack workflows adapted for Codex CLI and desktop with optional hybrid review and rescue.', 'developerName': 'huankoh, based on Lauren Tan’s pstack', 'category': 'Productivity', 'capabilities': [], 'defaultPrompt': 'Use $poteto-mode for this engineering task.'}}
            folder = target / '.codex-plugin'
            marketplace = output / runtime / '.agents/plugins'
            marketplace.mkdir(parents=True)
            # Relative to the marketplace root, not the manifest's containing directory.
            (marketplace / 'marketplace.json').write_text(json.dumps({'name': 'hstack', 'plugins': [{
                'name': NAME, 'source': {'source': 'local', 'path': './plugins/' + NAME},
                'policy': {'installation': 'AVAILABLE', 'authentication': 'ON_INSTALL'}, 'category': 'Productivity'}]}, indent=2) + '\n')
        else:
            manifest = dict(upstream, name=NAME, displayName='hstack', repository='https://github.com/huankoh/plugins',
                            version=upstream['version'] + '+hstack.' + fingerprint[:12])
            folder = target / '.cursor-plugin'
            marketplace = output / runtime / '.cursor-plugin'
            marketplace.mkdir(parents=True)
            (marketplace / 'marketplace.json').write_text(json.dumps({
                'name': NAME, 'owner': {'name': 'huankoh'},
                'plugins': [{'name': NAME, 'source': './plugins/' + NAME,
                             'description': 'hstack: pstack workflows with Codex review and rescue.'}]
            }, indent=2) + '\n')
        folder.mkdir(exist_ok=True)
        (folder / 'plugin.json').write_text(json.dumps(manifest, indent=2) + '\n')
        (target / 'BUILD.json').write_text(json.dumps({'runtime': runtime, 'source_revision': revision,
            'source_sha256': fingerprint, 'upstream_version': upstream['version']}, indent=2) + '\n')
    return {'output': str(output), 'source_revision': revision, 'source_sha256': fingerprint}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=SOURCE.parent / 'dist/hstack')
    print(json.dumps(build(parser.parse_args().output), indent=2))
